services:
  frontend:
    build: ./frontend
    depends_on:
      - backend
    restart: always
  backend:
    build: ./backend
    restart: always
    depends_on:
      - db
    environment:
      POSTGRES_PASSWORD: "P9vL7qX2nFm8Rw4Tc1Zy6HbKs"
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    restart: always
  db:
    image: postgres:18.4
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: "P9vL7qX2nFm8Rw4Tc1Zy6HbKs"
    ports:
      - "5432:5432"
    volumes:
      - react_flask_app_postgres_data:/var/lib/postgresql

volumes:
  react_flask_app_postgres_data:
